name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ILYAS_SECRET }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@52.221.236.60 << 'EOF'
          # Masuk ke direktori project
          cd /var/www/html/UTS-CC

          # Set safe directory supaya git aman
          git config --global --add safe.directory /var/www/html/UTS-CC

          # Tarik perubahan terbaru
          git fetch origin
          git reset --hard origin/main

          # Set permission (kalau perlu)
          sudo chown -R ec2-user:ec2-user /var/www/html/UTS-CC
          sudo chmod -R 755 /var/www/html/UTS-CC

          # Restart server
          sudo systemctl restart httpd
        EOF
        